# Generated by Django 2.2.7 on 2019-11-08 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('encoding', models.CharField(max_length=20)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('minutes', models.IntegerField(default=0)),
                ('seconds', models.IntegerField(default=0)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='url_parser.UrlInfo')),
            ],
        ),
    ]
