# Generated by Django 2.2.7 on 2019-11-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsertask',
            name='result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='url_parser.UrlInfo'),
        ),
    ]
