# Generated by Django 2.2.7 on 2019-11-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_parser', '0002_auto_20191108_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlinfo',
            name='encoding',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='urlinfo',
            name='site_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='urlinfo',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
