# Generated by Django 2.2.7 on 2019-11-10 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_parser', '0003_auto_20191110_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlinfo',
            name='message',
            field=models.CharField(default='page parsed successful', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsertask',
            name='result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='url_parser.UrlInfo'),
        ),
    ]
