# Generated by Django 2.2.7 on 2019-11-11 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_parser', '0004_auto_20191110_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlinfo',
            name='parsed_successful',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parsertask',
            name='minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parsertask',
            name='seconds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
